version: '3'
services:
  magic-batch:
    build: .
    hostname: magic-batch
    environment:
     - JAVA_OPTS=-Xmx256m -Xms128m
    ports:
     - "8080:8080"
    depends_on:
     - "magic-redis"
  magic-redis:
    hostname: magic-redis
    image: "redis:3.2.11"
    ports:
     - "6379:6379"